---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/airlines":
    post:
      summary: Creates an airline
      tags:
      - Arlines
      consumes:
      - application/json
      - application/xml
      parameters:
      - name: airline
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
      responses:
        '201':
          description: airline created
        '422':
          description: invalid request
  "/airlines/{id}":
    get:
      summary: Retrieves an airline
      tags:
      - Airlines
      produces:
      - application/json
      - application/xml
      parameters:
      - name: id
        in: path
        type: string
        required: true
      responses:
        '200':
          description: airline found
          schema:
            type: object
            properties:
              id:
                type: integer
              name:
                type: string
            required:
            - id
            - name
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
